openapi: 3.1.0
info:
  title: Shopping Application API
  version: 1.0.0
  description: API for a Shopping Application with various features including login, item management, payment processing, and order management.

servers:
  - url: https://api.shoppingapp.com/v1

paths:
  /login:
    post:
      summary: User Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authentication
        '401':
          description: Unauthorized

  /items:
    post:
      summary: Add Item to Cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - itemId
                - quantity
              properties:
                itemId:
                  type: string
                  example: abc123
                quantity:
                  type: integer
                  example: 2
      responses:
        '201':
          description: Item added successfully
        '400':
          description: Bad Request

  /payment:
    post:
      summary: Process Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - type: object
                  required:
                    - amount
                    - paymentMethod
                  properties:
                    amount:
                      type: number
                      format: float
                      example: 100.00
                    paymentMethod:
                      oneOf:
                        - $ref: '#/components/schemas/CreditCard'
                        - $ref: '#/components/schemas/PayPal'
      responses:
        '200':
          description: Payment successful
        '400':
          description: Payment failed

  /wishlist:
    post:
      summary: Add Item to Wishlist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - itemId
              properties:
                itemId:
                  type: string
                  example: abc123
      responses:
        '201':
          description: Item added to wishlist

  /orders:
    get:
      summary: View Orders
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

components:
  schemas:
    CreditCard:
      type: object
      required:
        - cardNumber
        - expirationDate
        - cvv
      properties:
        cardNumber:
          type: string
          example: "4111-1111-1111-1111"
        expirationDate:
          type: string
          example: "12/25"
        cvv:
          type: string
          example: "123"

    PayPal:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          example: user@example.com

    Order:
      type: object
      required:
        - orderId
        - items
        - status
      properties:
        orderId:
          type: string
          example: order123
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        status:
          type: string
          enum: [pending, completed, cancelled]
          example: completed

    OrderItem:
      type: object
      required:
        - itemId
        - quantity
      properties:
        itemId:
          type: string
          example: abc123
        quantity:
          type: integer
          example: 2